// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAB6khqmMuP0KMZneI5xNzIpS0GkoCuzA',
    appId: '1:812151452516:web:b659f2b2498d7979118071',
    messagingSenderId: '812151452516',
    projectId: 'spendsense-b8559',
    authDomain: 'spendsense-b8559.firebaseapp.com',
    databaseURL: 'https://spendsense-b8559-default-rtdb.firebaseio.com',
    storageBucket: 'spendsense-b8559.firebasestorage.app',
    measurementId: 'G-LDX5QNNY9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXInOXd6E6B5uj9XT2LCurBxelH-vu3TQ',
    appId: '1:812151452516:android:c87952e773390e1c118071',
    messagingSenderId: '812151452516',
    projectId: 'spendsense-b8559',
    databaseURL: 'https://spendsense-b8559-default-rtdb.firebaseio.com',
    storageBucket: 'spendsense-b8559.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2fzV9uAwHNCh3w9bGDdcO7dKghwvuKRA',
    appId: '1:812151452516:ios:35d413196d1b9830118071',
    messagingSenderId: '812151452516',
    projectId: 'spendsense-b8559',
    databaseURL: 'https://spendsense-b8559-default-rtdb.firebaseio.com',
    storageBucket: 'spendsense-b8559.firebasestorage.app',
    iosBundleId: 'com.tracker.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2fzV9uAwHNCh3w9bGDdcO7dKghwvuKRA',
    appId: '1:812151452516:ios:35d413196d1b9830118071',
    messagingSenderId: '812151452516',
    projectId: 'spendsense-b8559',
    databaseURL: 'https://spendsense-b8559-default-rtdb.firebaseio.com',
    storageBucket: 'spendsense-b8559.firebasestorage.app',
    iosBundleId: 'com.tracker.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAB6khqmMuP0KMZneI5xNzIpS0GkoCuzA',
    appId: '1:812151452516:web:cf2c8aa2e819e370118071',
    messagingSenderId: '812151452516',
    projectId: 'spendsense-b8559',
    authDomain: 'spendsense-b8559.firebaseapp.com',
    databaseURL: 'https://spendsense-b8559-default-rtdb.firebaseio.com',
    storageBucket: 'spendsense-b8559.firebasestorage.app',
    measurementId: 'G-5VKTQL1BZ1',
  );
}
