import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../models/monthly_budget.dart';
import '../models/transaction.dart';
import '../providers/expense_provider.dart';
import '../screens/budget_screen.dart';

class BudgetProgressCard extends StatelessWidget { const BudgetProgressCard({super.key}); @override Widget build(BuildContext context){final provider=ExpenseScope.of(context);final now=DateTime.now();final budgets=provider.budgetsForMonth(now.year,now.month);return Card(child:InkWell(borderRadius:BorderRadius.circular(16),onTap:()=>Navigator.of(context).push(MaterialPageRoute<void>(builder:(_)=>const BudgetScreen())),child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text('Monthly budgets',style:Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.w700))),TextButton(onPressed:()=>Navigator.of(context).push(MaterialPageRoute<void>(builder:(_)=>const BudgetScreen())),child:Text(budgets.isEmpty?'Set budget':'Manage'))]),if(budgets.isEmpty) const Text('Set a spending limit and track what remains this month.') else ...budgets.take(3).map((b)=>_ProgressRow(budget:b,transactions:provider.transactions))]))));}}
class _ProgressRow extends StatelessWidget {const _ProgressRow({required this.budget,required this.transactions});final MonthlyBudget budget;final List<Transaction> transactions;@override Widget build(BuildContext context){final spent=BudgetAnalytics.spentFor(transactions,budget);final ratio=BudgetAnalytics.usageRatio(transactions,budget);final color=ratio>=1?Theme.of(context).colorScheme.error:ratio>=.8?Colors.orange:Theme.of(context).colorScheme.secondary;final fmt=NumberFormat.currency(symbol:budget.currency.symbol,decimalDigits:0);return Padding(padding:const EdgeInsets.only(top:10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(budget.category?.displayName??'Overall',style:Theme.of(context).textTheme.bodyMedium)),Text('${(ratio*100).round()}%')]),const SizedBox(height:6),LinearProgressIndicator(value:ratio.clamp(0.0,1.0).toDouble(),color:color),const SizedBox(height:4),Text('${fmt.format(spent)} spent · ${fmt.format(BudgetAnalytics.remaining(transactions,budget))} remaining',style:Theme.of(context).textTheme.bodySmall)]));}}
