import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:intl/intl.dart';
import '../models/category.dart';
import '../models/monthly_budget.dart';
import '../models/transaction.dart';
import '../providers/expense_provider.dart';

class BudgetScreen extends StatefulWidget { const BudgetScreen({super.key}); @override State<BudgetScreen> createState()=>_BudgetScreenState(); }
class _BudgetScreenState extends State<BudgetScreen> {
 final _amount=TextEditingController(); ExpenseCategory? _category; TransactionCurrency _currency=TransactionCurrency.inr; bool _saving=false;
 @override void dispose(){_amount.dispose();super.dispose();}
 Future<void> _save() async { final amount=double.tryParse(_amount.text.trim()); if(amount==null||amount<=0){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Enter a valid budget amount.')));return;} setState(()=>_saving=true); try {await ExpenseScope.of(context).saveBudget(year:DateTime.now().year,month:DateTime.now().month,amount:amount,currency:_currency,category:_category); _amount.clear(); if(mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Monthly budget saved.')));} catch(error){debugPrint('Budget save failed: $error');if(mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Could not save budget: $error')));} finally{if(mounted)setState(()=>_saving=false);} }
 @override Widget build(BuildContext context){ final provider=ExpenseScope.of(context); final now=DateTime.now(); final budgets=provider.budgetsForMonth(now.year,now.month); final month=DateFormat('MMMM yyyy').format(now); return Scaffold(appBar:AppBar(title:const Text('Smart Budgets')),body:ListView(padding:const EdgeInsets.all(20),children:[Text(month,style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:16),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text('Set a monthly budget',style:Theme.of(context).textTheme.titleMedium),const SizedBox(height:12),TextField(controller:_amount,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:InputDecoration(labelText:'Amount',prefixText:'${_currency.symbol} ')),const SizedBox(height:12),DropdownButtonFormField<TransactionCurrency>(value:_currency,decoration:const InputDecoration(labelText:'Currency'),items:TransactionCurrency.values.where((c)=>c!=TransactionCurrency.unknown).map((c)=>DropdownMenuItem(value:c,child:Text(c.displayName))).toList(),onChanged:(v){if(v!=null)setState(()=>_currency=v);}),const SizedBox(height:12),DropdownButtonFormField<ExpenseCategory?>(value:_category,decoration:const InputDecoration(labelText:'Budget type'),items:[const DropdownMenuItem<ExpenseCategory?>(value:null,child:Text('Overall spending')), ...ExpenseCategory.values.where((c)=>c!=ExpenseCategory.salary).map((c)=>DropdownMenuItem<ExpenseCategory?>(value:c,child:Text(c.displayName)))],onChanged:(v)=>setState(()=>_category=v)),const SizedBox(height:12),FilledButton(onPressed:_saving?null:_save,child:Text(_saving?'Saving…':'Save budget'))]))),const SizedBox(height:20),Text('This month',style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:8),if(budgets.isEmpty) const Card(child:Padding(padding:EdgeInsets.all(16),child:Text('No budgets set for this month yet.'))) else ...budgets.map((b)=>_BudgetTile(budget:b,onDelete:()=>provider.deleteBudget(b))) ])); }
}
class _BudgetTile extends StatelessWidget {const _BudgetTile({required this.budget,required this.onDelete});final MonthlyBudget budget;final VoidCallback onDelete; @override Widget build(BuildContext context){final transactions=ExpenseScope.of(context).transactions;final spent=BudgetAnalytics.spentFor(transactions,budget);final ratio=BudgetAnalytics.usageRatio(transactions,budget);final color=ratio>=1?Theme.of(context).colorScheme.error:ratio>=.8?Colors.orange:Theme.of(context).colorScheme.secondary;final money=NumberFormat.currency(symbol:budget.currency.symbol,decimalDigits:0);return Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(budget.category?.displayName??'Overall spending',style:Theme.of(context).textTheme.titleMedium)),IconButton(onPressed:onDelete,icon:const Icon(Icons.delete_outline),tooltip:'Delete budget')]),LinearProgressIndicator(value:ratio.clamp(0.0,1.0).toDouble(),color:color),const SizedBox(height:10),Text('${money.format(spent)} spent of ${money.format(budget.amount)} · ${money.format(BudgetAnalytics.remaining(transactions,budget))} remaining'),Text('${(ratio*100).round()}% used',style:TextStyle(color:color,fontWeight:FontWeight.w700))])));}}
